"use client";

import { useMemo, useState } from "react";
import { Check, ChevronRight, SlidersHorizontal, Sparkles, Target } from "lucide-react";

const employeeOptions=["Any size","1-10","11-50","51-200","201-500","500+"];

export default function ICPBuilder(){
 const [industry,setIndustry]=useState("SaaS"); const [location,setLocation]=useState("United States"); const [employees,setEmployees]=useState("11-50"); const [roles,setRoles]=useState("Founder, CEO, VP Sales"); const [keywords,setKeywords]=useState("B2B, workflow, automation"); const [saved,setSaved]=useState(false);
 const summary=useMemo(()=>[industry,location,employees,roles].filter(Boolean),[industry,location,employees,roles]);
 return <main className="min-h-screen bg-[#07111f] text-slate-100"><div className="mx-auto max-w-7xl px-6 py-8 lg:px-10">
  <header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-xs uppercase tracking-widest text-cyan-300">Targeting</p><h1 className="mt-1 text-2xl font-semibold">Ideal Customer Profile</h1><p className="mt-2 text-sm text-slate-500">Define who the prospecting engine should look for.</p></div><a href="/dashboard" className="text-sm text-slate-400 hover:text-white">Dashboard</a></header>
  <div className="grid gap-6 py-8 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2 font-medium"><SlidersHorizontal size={17} className="text-cyan-300"/>Profile criteria</div>
   <div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Industry"><input value={industry} onChange={e=>setIndustry(e.target.value)} className="input" placeholder="e.g. SaaS"/></Field><Field label="Location"><input value={location} onChange={e=>setLocation(e.target.value)} className="input" placeholder="Country, city or region"/></Field><Field label="Employee range"><select value={employees} onChange={e=>setEmployees(e.target.value)} className="input">{employeeOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Decision-maker roles"><input value={roles} onChange={e=>setRoles(e.target.value)} className="input" placeholder="Founder, CEO, Head of Sales"/></Field><div className="sm:col-span-2"><Field label="Keywords / technologies"><textarea value={keywords} onChange={e=>setKeywords(e.target.value)} rows={4} className="input resize-none" placeholder="Separate terms with commas"/></Field></div></div>
   <button onClick={()=>setSaved(true)} className="mt-6 flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-semibold text-slate-950">{saved?<Check size={16}/>:<Target size={16}/>} {saved?"ICP saved locally":"Save ICP"}</button>
  </section><aside className="h-fit rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2 font-medium"><Sparkles size={17} className="text-cyan-300"/>Targeting preview</div><p className="mt-2 text-sm leading-6 text-slate-500">This profile will feed company discovery, lead matching and scoring providers later.</p><div className="mt-5 space-y-2">{summary.map(x=><div key={x} className="flex items-center gap-2 rounded-lg border border-white/5 bg-white/[.025] px-3 py-2 text-xs text-slate-300"><ChevronRight size={13} className="text-cyan-300"/>{x}</div>)}</div><div className="mt-5 rounded-xl border border-cyan-400/10 bg-cyan-400/5 p-4"><p className="text-xs font-medium text-cyan-300">Provider independent</p><p className="mt-1 text-xs leading-5 text-slate-500">No enrichment, search or AI API key is required yet.</p></div></aside></div>
 </div><style jsx>{`.input{margin-top:.5rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.03);padding:.75rem .9rem;font-size:.875rem;outline:none;color:#e2e8f0}.input:focus{border-color:rgba(34,211,238,.4)}select.input option{background:#0b1828}`}</style></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs text-slate-400"><span>{label}</span>{children}</label>}
