"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Bot, Building2, Mail, Sparkles, Star, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
const data:Record<string,{id:string;name:string;title:string;company:string;email:string;score:number;status:string;reasons:string[]}>={
p1:{id:"p1",name:"Sarah Khan",title:"Founder & CEO",company:"Northstar Software",email:"sarah@northstar.example",score:92,status:"Qualified",reasons:["Decision-maker role","Target company profile match","B2B workflow context"]},
p2:{id:"p2",name:"Omar Ahmed",title:"Managing Director",company:"Vertex Digital",email:"omar@vertex.example",score:84,status:"New",reasons:["Senior decision maker","Technology services fit","Company data available"]},
p3:{id:"p3",name:"Daniel Reed",title:"Founder",company:"Summit Growth",email:"daniel@summit.example",score:78,status:"Contacted",reasons:["Founder role","Marketing agency fit","Relevant company profile"]}};
export default function LeadDetail({params}:{params:{id:string}}){const lead=data[params.id]??data.p1;const [result,setResult]=useState<{subject:string;body:string}|null>(null);const [loading,setLoading]=useState(false);
async function personalize(){setLoading(true);try{const r=await fetch("/api/ai/personalize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lead,status:lead.status.toLowerCase(),product:"AI sales automation platform"})});const d=await r.json();if(r.ok)setResult(d);}finally{setLoading(false)}}
return <AppShell><div className="max-w-5xl"><Link href="/leads" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-white"><ArrowLeft size={15}/>Back to leads</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><UserRound size={24}/></div><div><h1 className="text-2xl font-semibold">{lead.name}</h1><p className="mt-1 text-slate-400">{lead.title} · {lead.company}</p><p className="mt-2 flex items-center gap-2 text-xs text-slate-500"><Mail size={13}/>{lead.email}</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-slate-500">AI fit score</p><p className="mt-2 flex items-center gap-2 text-2xl font-semibold"><Star size={18} className="text-cyan-300"/>{lead.score}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-slate-500">Status</p><p className="mt-2 text-sm">{lead.status}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-slate-500">Provider</p><p className="mt-2 text-sm text-emerald-300">Mock</p></div></div><div className="mt-8"><h2 className="font-medium">Why this lead scored</h2><div className="mt-3 space-y-2">{lead.reasons.map(x=><div key={x} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[.02] p-3 text-sm text-slate-400"><Sparkles size={14} className="text-cyan-300"/>{x}</div>)}</div></div></section><aside className="h-fit rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2 font-medium"><Bot size={17} className="text-cyan-300"/>AI outreach</div><p className="mt-2 text-sm leading-6 text-slate-500">Generate a personalized draft through the active AI provider.</p><button onClick={personalize} disabled={loading} className="mt-5 w-full rounded-lg bg-cyan-400 py-3 text-sm font-semibold text-slate-950 disabled:opacity-50">{loading?"Generating…":"Generate personalization"}</button>{result&&<div className="mt-5 rounded-xl border border-white/10 bg-black/10 p-4"><p className="text-xs font-medium text-cyan-300">{result.subject}</p><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-400">{result.body}</p></div>}<div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Building2 size={13}/>Company context included</div></aside></div></div></AppShell>}
