"use client";
import { useState } from "react";
import { Bot, Check, Mail, Search, Star, UserRound } from "lucide-react";
const leads=[{id:"p1",name:"Sarah Khan",title:"Founder & CEO",company:"Northstar Software",email:"sarah@northstar.example",score:92,status:"Qualified"},{id:"p2",name:"Omar Ahmed",title:"Managing Director",company:"Vertex Digital",email:"omar@vertex.example",score:84,status:"New"},{id:"p3",name:"Daniel Reed",title:"Founder",company:"Summit Growth",email:"daniel@summit.example",score:78,status:"Contacted"}];
export default function Leads(){
 const [q,setQ]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [scores,setScores]=useState<Record<string,number>>({}); const [loading,setLoading]=useState("");
 const filtered=leads.filter(x=>(x.name+" "+x.company+" "+x.title).toLowerCase().includes(q.toLowerCase()));
 async function score(id:string){const lead=leads.find(x=>x.id===id);if(!lead)return;setLoading(id);try{const r=await fetch("/api/leads/score",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...lead,status:lead.status.toLowerCase()})});const data=await r.json();if(r.ok)setScores(s=>({...s,[id]:data.score}));}finally{setLoading("");}}
 return <main className="min-h-screen bg-[#07111f] text-slate-100"><div className="mx-auto max-w-7xl px-6 py-8 lg:px-10"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-xs uppercase tracking-widest text-cyan-300">Prospecting</p><h1 className="mt-1 text-2xl font-semibold">Lead Finder</h1></div><a href="/dashboard" className="text-sm text-slate-400">Dashboard</a></header><div className="mt-8 flex gap-3"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people, companies or roles..." className="w-full rounded-xl border border-white/10 bg-white/[.04] py-3 pl-10 pr-4 text-sm outline-none"/></div><button onClick={()=>setSelected(filtered.map(x=>x.id))} className="rounded-xl border border-white/10 px-4 text-sm">Select all</button></div><div className="mt-5 space-y-3">{filtered.map(l=><div key={l.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center gap-4"><button onClick={()=>setSelected(s=>s.includes(l.id)?s.filter(x=>x!==l.id):[...s,l.id])} className={`flex h-5 w-5 items-center justify-center rounded border ${selected.includes(l.id)?"border-cyan-400 bg-cyan-400 text-slate-950":"border-white/20"}`}>{selected.includes(l.id)&&<Check size={13}/>}</button><div className="flex h-11 w-11 items-center justify-center rounded-full bg-white/5"><UserRound size={20}/></div><div className="min-w-0 flex-1"><h2 className="font-medium">{l.name}</h2><p className="text-sm text-slate-400">{l.title} · {l.company}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><Mail size={12}/>{l.email}</p></div><div className="hidden items-center gap-1 rounded-lg bg-emerald-400/10 px-3 py-2 text-sm text-emerald-300 sm:flex"><Star size={14}/>{scores[l.id]??l.score}</div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-400">{l.status}</span></div><div className="mt-4 flex justify-end gap-2 border-t border-white/5 pt-4"><button onClick={()=>score(l.id)} disabled={loading===l.id} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-50"><Bot size={14}/>{loading===l.id?"Scoring...":"AI score"}</button><a href={`/leads/${l.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs">View lead</a><button className="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-semibold text-slate-950">Add to campaign</button></div></div>)}</div></div></main>
}