"use client";
import { AppShell } from "@/components/app-shell";
import { useEffect, useState } from "react";
import { Clock3, Mail, Play, Plus, Sparkles } from "lucide-react";
export default function Campaigns(){
 const [steps,setSteps]=useState(["Initial outreach","Follow-up #1","Follow-up #2"]); const [status,setStatus]=useState(""); const [campaignId,setCampaignId]=useState("cmp-1"); const [loaded,setLoaded]=useState(false);
 useEffect(()=>{fetch("/api/campaigns").then(r=>r.ok?r.json():null).then(d=>{const x=d?.campaigns?.[0];if(x){setCampaignId(x.id);setSteps(Array.from({length:Math.max(1,x.steps)},(_,i)=>i===0?"Initial outreach":`Follow-up #${i}`))}setLoaded(true)}).catch(()=>setLoaded(true))},[]);
 async function saveCampaign(nextSteps=steps){await fetch("/api/campaigns",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:campaignId,steps:nextSteps.length})});}

 const addStep=()=>{const next=[...steps,"Follow-up #"+(steps.length+1)];setSteps(next);void saveCampaign(next)};
 async function run(){setStatus("Queueing...");try{const r=await fetch("/api/campaigns/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId,emails:[{to:"sarah@northstar.example",subject:"Idea for Northstar Software",body:"Hi Sarah, I thought our workflow could be relevant to Northstar Software."}]})});const data=await r.json();setStatus(r.ok?`${data.queued} message queued in review mode`:"Campaign failed");}catch{setStatus("Campaign failed");}}
 return <AppShell><div className="mx-auto max-w-6xl px-6 py-8 lg:px-10"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-xs uppercase tracking-widest text-cyan-300">Outreach</p><h1 className="mt-1 text-2xl font-semibold">Campaign Builder</h1></div><a href="/dashboard" className="text-sm text-slate-400">Dashboard</a></header><div className="grid gap-6 py-8 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center justify-between"><div><h2 className="font-medium">New outbound sequence</h2><p className="mt-1 text-sm text-slate-500">Build the sequence now. Sending remains review-only in local mode.</p></div><button onClick={addStep} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm"><Plus size={15}/> Add step</button></div><div className="mt-7 space-y-3">{steps.map((step,i)=><div key={step} className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-cyan-400/10 text-xs text-cyan-300">{i+1}</span><span className="font-medium text-sm">{step}</span>{i>0&&<span className="ml-auto flex items-center gap-1 text-xs text-slate-500"><Clock3 size={13}/>{i*2} days</span>}</div><div className="mt-4 rounded-lg border border-white/5 bg-white/[.025] p-4"><div className="flex items-center gap-2 text-xs text-slate-500"><Mail size={14}/> Email message</div><p className="mt-3 text-sm text-slate-400">{i===0?"Hi {{first_name}}, I noticed {{company}} and thought our solution may be relevant to your team.":"Following up on my previous note. Would a short conversation be useful?"}</p></div></div>)}</div></section><aside className="rounded-2xl border border-white/10 bg-white/[.035] p-6 h-fit"><div className="flex items-center gap-2 font-medium"><Sparkles size={17} className="text-cyan-300"/> AI personalization</div><p className="mt-2 text-sm leading-6 text-slate-500">The AI provider will personalize each message from lead and company context.</p><button onClick={run} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-400 py-3 text-sm font-semibold text-slate-950"><Play size={15}/>{status||"Run local test"}</button><div className="mt-6 space-y-3 text-xs text-slate-500"><div className="flex justify-between"><span>Audience</span><span className="text-slate-300">42 leads</span></div><div className="flex justify-between"><span>Steps</span><span className="text-slate-300">{steps.length}</span></div><div className="flex justify-between"><span>Provider</span><span className="text-emerald-300">Mock / review</span></div></div></aside></div></div></AppShell>;
}